export const mockData = [
  {
    id: 1,
    name: "Jenn Janson",
    position: "VP of Makreting",
    company: "RGC",
    activity: "Last response a week ago",
    status: "happyBoy",
  },
  {
    id: 2,
    name: "Alex Abrams",
    position: "Marketing Manager",
    company: "AirNinja",
    activity: "New email",
    status: "champBoy",
  },
  {
    id: 3,
    name: "Tom Tollins",
    position: "Position",
    company: "AirNinja",
    activity: "...",
    status: "sadBoy",
  },
  {
    id: 4,
    name: "Tyler Middleton",
    position: "Position",
    company: "RGC",
    activity: "...",
    status: "indiffBoy",
  },
  {
    id: 5,
    name: "Rick Mighty",
    position: "Marketing Manager",
    company: "RGC",
    activity: "...",
    status: "indiffBoy",
  },
  {
    id: 6,
    name: "Anne Nicely",
    position: "Head of Sales",
    company: "Walk About",
    activity: "...",
    status: "happyGirl",
  },
  {
    id: 7,
    name: "Alex Stevenson",
    position: "General Manager",
    company: "Walk About",
    activity: "...",
    status: "champBoy",
  },
  {
    id: 8,
    name: "Mark Roberts",
    position: "Marketing Executive",
    company: "Looking Glass",
    activity: "...",
    status: "curiousBoy",
  },
  {
    id: 9,
    name: "Tale Storm",
    position: "Manager",
    company: "Slack",
    activity: "Last response today",
    status: "happyBoy",
  },
  {
    id: 10,
    name: "Emma Jones",
    position: "General Manager",
    company: "Walk About",
    activity: "New email",
    status: "champGirl",
  },
  {
    id: 11,
    name: "Vanessa Aubrey",
    position: "Communication Manager",
    company: "BlockFlow",
    activity: "...",
    status: "sadGirl",
  },
  {
    id: 12,
    name: "Tyler Middleton",
    position: "Position",
    company: "Facebook",
    activity: "...",
    status: "indiffBoy",
  },
  {
    id: 13,
    name: "Rick Mighty",
    position: "Position",
    company: "Facebook",
    activity: "...",
    status: "indiffBoy",
  },
  {
    id: 14,
    name: "Grace Gathers",
    position: "Region Assistant Manager",
    company: "Jumpr",
    activity: "...",
    status: "happyGirl",
  },
  {
    id: 15,
    name: "Ben Holloway",
    position: "Director of PR",
    company: "SendDoc",
    activity: "...",
    status: "happyBoy",
  },
];

export const mockMoods = {
  happyBoy: "boy_happy.gif",
  sadBoy: "boy_sad.gif",
  champBoy: "boy_champ.gif",
  indiffBoy: "boy_indifferent.gif",
};

export const moodFilterData = [
  {
    id: "all",
    name: "All",
  },
  {
    id: "champ",
    name: "Champion",
  },
  {
    id: "sad",
    name: "Need Attention",
  },
  {
    id: "cold",
    name: "Cold",
  },
  {
    id: "risk",
    name: "At Risk",
  },
];
