export const mockData = [
  {
    id: 1,
    name: "Jenn Janson",
    position: "VP of Makreting",
    company: "RGC",
    activity: "Last response a week ago",
    status: "happyBoy",
    health: 4.5,
    strategy: [],
    renewalDate: "12/10/2020",
  },
  {
    id: 2,
    name: "Alex Abrams",
    position: "Marketing Manager",
    company: "AirNinja",
    activity: "New email",
    status: "champBoy",
    health: 5,
    strategy: [],
    renewalDate: "02/10/2021",
  },
  {
    id: 3,
    name: "Tom Tollins",
    position: "Position",
    company: "AirNinja",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "sadBoy",
    health: 2,
    strategy: ["attention"],
    renewalDate: "12/10/2020",
  },
  {
    id: 4,
    name: "Tyler Middleton",
    position: "Position",
    company: "RGC",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "indiffBoy",
    health: 2.4,
    strategy: ["attention", "bug"],
    renewalDate: "12/20/2020",
  },
  {
    id: 5,
    name: "Rick Mighty",
    position: "Marketing Manager",
    company: "RGC",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "indiffBoy",
    health: 2.4,
    strategy: ["bug"],
    renewalDate: "11/18/2020",
  },
  {
    id: 6,
    name: "Anne Nicely",
    position: "Head of Sales",
    company: "Walk About",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "happyGirl",
    health: 4.5,
    strategy: [],
    renewalDate: "12/10/2020",
  },
  {
    id: 7,
    name: "Alex Stevenson",
    position: "General Manager",
    company: "Walk About",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "champBoy",
    health: 5,
    strategy: [],
    renewalDate: "12/10/2020",
  },
  {
    id: 8,
    name: "Mark Roberts",
    position: "Marketing Executive",
    company: "Looking Glass",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "curiousBoy",
    health: 3,
    strategy: [],
    renewalDate: "12/10/2020",
  },
  {
    id: 9,
    name: "Tale Storm",
    position: "Manager",
    company: "Slack",
    activity: "Last response today",
    status: "happyBoy",
    health: 4.3,
    strategy: [],
    renewalDate: "12/10/2020",
  },
  {
    id: 10,
    name: "Emma Jones",
    position: "General Manager",
    company: "Walk About",
    activity: "New email",
    status: "champGirl",
    health: 4.9,
    strategy: [],
    renewalDate: "12/10/2020",
  },
  {
    id: 11,
    name: "Vanessa Aubrey",
    position: "Communication Manager",
    company: "BlockFlow",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "sadGirl",
    health: 1.9,
    strategy: ["escalate", "contact"],
    renewalDate: "12/10/2020",
  },
  {
    id: 12,
    name: "Tyler Middleton",
    position: "Position",
    company: "Facebook",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "indiffBoy",
    health: 3.1,
    strategy: [],
    renewalDate: "11/10/2020",
  },
  {
    id: 13,
    name: "Rick Mighty",
    position: "Position",
    company: "Facebook",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "indiffBoy",
    health: 3.2,
    strategy: [],
    renewalDate: "12/10/2021",
  },
  {
    id: 14,
    name: "Grace Gathers",
    position: "Region Assistant Manager",
    company: "Jumpr",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "happyGirl",
    health: 4.2,
    strategy: [],
    renewalDate: "05/20/2021",
  },
  {
    id: 15,
    name: "Ben Holloway",
    position: "Director of PR",
    company: "SendDoc",
    activity: "...",
    status: "happyBoy",
    health: 4.2,
    strategy: [],
    renewalDate: "04/10/2021",
  },
];

export const mockMoods = {
  happyBoy: "boy_happy.gif",
  sadBoy: "boy_sad.gif",
  champBoy: "boy_champ.gif",
  indiffBoy: "boy_indifferent.gif",
};

export const notesMock = [
  {
    id: 20,
    clientId: 4,
    contactId: 2,
    createdAt: "6/19/20 1:34 PM",
    title: "Video chat going over our new features",
    text:
      "I went over our new features in our latest update to make sure Mike is comfortable using them and understands the value they can add for his team. I will follow up on this with an email next week.",
  },
  {
    id: 21,
    clientId: 4,
    contactId: 2,
    createdAt: "6/19/20 1:34 PM",
    title: "More focus on social marketing",
    text:
      "I’ve been sending more email touchpoints with a social marketing focus lately. I think our social marketing features will really help AirNinja grow their social presence. Mike seems interested in utilizing more of our...",
  },
  {
    id: 22,
    clientId: 4,
    contactId: 2,
    createdAt: "6/19/20 1:34 PM",
    title: "Video chat going over our new features",
    text:
      "Chatted with Mike about a bug he is currently experiencing. He is having trouble getting his other team members signed up on the platform. I assigned a bug badge with further notes to the account and will follow...",
  },
  {
    id: 26,
    clientId: 4,
    contactId: 2,
    createdAt: "6/19/20 1:34 PM",
    title: "Video chat going over our new features",
    text:
      "Chatted with Mike about a bug he is currently experiencing. He is having trouble getting his other team members signed up on the platform. I assigned a bug badge with further notes to the account and will follow...",
  },
];
