export const mockData = [
  {
    id: 1,
    name: "Jenn Janson",
    position: "VP of Makreting",
    company: "RGC",
    activity: "Last response a week ago",
    status: "happyBoy",
    health: 4.5,
    strategy: [],
  },
  {
    id: 2,
    name: "Alex Abrams",
    position: "Marketing Manager",
    company: "AirNinja",
    activity: "New email",
    status: "champBoy",
    health: 5,
    strategy: [],
  },
  {
    id: 3,
    name: "Tom Tollins",
    position: "Position",
    company: "AirNinja",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "sadBoy",
    health: 2,
    strategy: ["attention"],
  },
  {
    id: 4,
    name: "Tyler Middleton",
    position: "Position",
    company: "RGC",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "indiffBoy",
    health: 2.4,
    strategy: ["attention", "bug"],
  },
  {
    id: 5,
    name: "Rick Mighty",
    position: "Marketing Manager",
    company: "RGC",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "indiffBoy",
    health: 2.4,
    strategy: ["bug"],
  },
  {
    id: 6,
    name: "Anne Nicely",
    position: "Head of Sales",
    company: "Walk About",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "happyGirl",
    health: 4.5,
    strategy: [],
  },
  {
    id: 7,
    name: "Alex Stevenson",
    position: "General Manager",
    company: "Walk About",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "champBoy",
    health: 5,
    strategy: [],
  },
  {
    id: 8,
    name: "Mark Roberts",
    position: "Marketing Executive",
    company: "Looking Glass",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "curiousBoy",
    health: 3,
    strategy: [],
  },
  {
    id: 9,
    name: "Tale Storm",
    position: "Manager",
    company: "Slack",
    activity: "Last response today",
    status: "happyBoy",
    health: 4.3,
    strategy: [],
  },
  {
    id: 10,
    name: "Emma Jones",
    position: "General Manager",
    company: "Walk About",
    activity: "New email",
    status: "champGirl",
    health: 4.9,
    strategy: [],
  },
  {
    id: 11,
    name: "Vanessa Aubrey",
    position: "Communication Manager",
    company: "BlockFlow",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "sadGirl",
    health: 1.9,
    strategy: ["escalate", "contact"],
  },
  {
    id: 12,
    name: "Tyler Middleton",
    position: "Position",
    company: "Facebook",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "indiffBoy",
    health: 3.1,
    strategy: [],
  },
  {
    id: 13,
    name: "Rick Mighty",
    position: "Position",
    company: "Facebook",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "indiffBoy",
    health: 3.2,
    strategy: [],
  },
  {
    id: 14,
    name: "Grace Gathers",
    position: "Region Assistant Manager",
    company: "Jumpr",
    activity: "Last activity is at 9:23PM on 24/08/2020",
    status: "happyGirl",
    health: 4.2,
    strategy: [],
  },
  {
    id: 15,
    name: "Ben Holloway",
    position: "Director of PR",
    company: "SendDoc",
    activity: "...",
    status: "happyBoy",
    health: 4.2,
    strategy: [],
  },
];

export const mockMoods = {
  happyBoy: "boy_happy.gif",
  sadBoy: "boy_sad.gif",
  champBoy: "boy_champ.gif",
  indiffBoy: "boy_indifferent.gif",
};
